language: android
dist: trusty

group: edge

sudo: false

cache:
  directories:
  - "$HOME/.gradle"

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-26
  - android-25
  - sys-img-arm64-v8a-google_apis-25
  - extra-android-m2repository

jdk:
- oraclejdk8

script:
- "./gradlew clean sherlock:testDebugUnitTest"
